### ISSUE TITLE
Upgrade to router v4 beta ?

### ISSUE THREAD

**Issue by Vincz** [gabrielbull/react-router-server#14]
Hi, i'm looking forward to use this library for a big project but i'm waiting for the api to stabilise a little bit. According to this https://github.com/ctrlplusb/react-universally/issues/356 , it seems the react router api should now be stable. Is there any plan to upgrade react-router-server to react-router beta ? Many thanks.

**Comment by gabrielbull** [comment]
This was done on Feb. 12 with release 2.1.0. I have now updated the example as well to use react-router 4.0.0
