### ISSUE TITLE
Example project with hot reloading

### ISSUE THREAD

**Issue by tobiasandersen** [gabrielbull/react-router-server#17]
Hi, great job with the project!

I'm trying to set up hot reloading with your [example project](https://github.com/gabrielbull/react-router-server-complex-example), but without any luck so far. Have you tried getting it running?

**Comment by gabrielbull** [comment]
Haven't tried with hot reloading yet, but I do want to have an example project that works with it.

**Comment by benceg** [comment]
Hi @tobiasandersen and @gabrielbull,

Did either of you get this working?

From what I can tell, there's an issue here with HMR preserving components' state within the component tree. Given that `module` is a key within `Module`'s state, HMR _is_ reloading the relevant code chunks but _is not_ updating or flushing each `Module` component's state. This means the UI does not update to reflect the reloaded module(s).

Some cursory Googling indicates that this is a fairly common problem, with no catch-all solution yet available.

**Comment by smarchetti** [comment]
In the meantime, I've published my fork of this with the above PR. You can access it here:

https://www.npmjs.com/package/react-router-server-hmr
