### ISSUE TITLE
deleted

### ISSUE THREAD

**Issue by dotnetwise** [gabrielbull/react-router-server#2]

**Comment by gabrielbull** [comment]
This library was made 3 years ago when there really was a need for it. Nowadays, the [srcset](http://www.webkit.org/demos/srcset/) is a better alternative.

**Comment by dotnetwise** [comment]
That's true, unless you target IOS, which only has partial support, or IE
which doesn't have at all.

Best Regards,
Laurenţiu Macovei
DotNetWise <http://www.dotnetwise.com>
