### ISSUE TITLE
code-split-component. Collaborate? :)

### ISSUE THREAD

**Issue by ctrlplusb** [gabrielbull/react-router-server#5]
Hi @gabrielbull!

Great project. :)

I had similar needs to you in needing code splitting on my react-router v4 routes.  I created a library to help with this.  I would appreciate it if you could have a look and let me know if there are any issues that I may have overlooked.

[`code-split-component`](https://github.com/ctrlplusb/code-split-component)

Thanks!

**Comment by gabrielbull** [comment]
Hi @ctrlplusb

I like how you use a component for the part that loads the module, much more React like. I'm ashamed I did not think of that, I will definitely steal your idea. Unless you'd like to contribute yourself, it would be nice to join efforts into a better solution for SSR for everyone, as it is a pain right now to get it right. Although this library is limited to react router, maybe it would be a good thing to separate the general SSR stuff from this library. Let me know your thoughts on this!

**Comment by ctrlplusb** [comment]
Hi @gabrielbull!

Great to get your feedback on this yes!  I also like the declarative look of that API.  It was originally inspired by Sunil Pai's [`react-modules`](https://github.com/threepointone/react-modules) library. I am glad to see you are making use of it too. :)

I am so glad to hear you are interested in collaborating.  I have actually completed an initial alpha model of a generic solution that is friendly to SSR environments, ensuring that chunk assets are rehydrated (in a similar manner from looking at your docs) to what you have here.  

Check it out: https://github.com/ctrlplusb/code-split-component

I am super interested in having you in collaborating with you to push this library forward and would greatly appreciate your opinion and experience with this topic.  

At the moment I have the current "issues":
- Hot module reloading is not supported.
- You have to configure a babel and a webpack plugin. Would be great if I could merge this somehow.
- The webpack plugin overrides the chunk and module id generation so that I can produce id's that I can easily resolve to. I am not sure if there is perhaps a cleaner / friendlier way of doing this.

I look forward to hearing from you! :)

**Comment by ctrlplusb** [comment]
P.S. I have resolved issue number 3 described above. We now have a test suite developing. :-)

**Comment by gabrielbull** [comment]
Does this mean you can get the module id from your component? Because this is what is required by this lib to make sure that the correct module has been preloaded before rendering on the client side.

**Comment by ctrlplusb** [comment]
I created a webpack plugin that maps a determinable hash representing a module against the id generated by the webpack bundling process for it.

**Comment by ctrlplusb** [comment]
Hey @gabrielbull!

I am closing this as I went a very different [route](https://www.npmjs.com/package/react-async-component).

✌️
