### ISSUE TITLE
Warning: setState called on an unmounted component

### ISSUE THREAD

**Issue by yormi** [gabrielbull/react-router-server#6]
Hi there !

First of all, thanks for your work !

I got an issue with it though and I was wondering how you would like to solve it.

> Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the _class component.

The faulty setState is in fact caused by:
https://github.com/gabrielbull/react-router-server/blob/master/src/fetchState.js#L60

I guess we should follow what's in here: https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html

What do you think ?

**Comment by gabrielbull** [comment]
Do you get this message on server side or client side?

**Comment by yormi** [comment]
Client side, during my tests. In the browser, I guess  we're to slow to
unmount the component before fetchState resolve in a normal use.

2016-10-29 0:23 GMT-04:00 Gabriel Bull notifications@github.com:

**Comment by gabrielbull** [comment]
Thanks for the fix! I published a new version 0.5.1 that includes it. 👍🏼

**Comment by yormi** [comment]
You're welcome ! It was quite simple. Thanks for the tough heavy work :)
